### ISSUE TITLE
[feature] include SAAS apps in show-relation

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/jhack#103]

**Comment by PietroPasotti** [comment]
@paulomach FYI the feature is already implemented but restricted: it only works if you are in the requirer model and you type `jhack show-relation provider:endpoint requirer:endpoint` (or something like that). Something due to how hard it is to chase down the data I need in show-unit and status.

I just merged an update that makes the heuristic more powerful and removes these limitations.
Check it out as soon as it's released on edge!

**Comment by paulomach** [comment]
Thank you!
