### ISSUE TITLE
`jhack sync <application-name>/<unit-number>` returns `ValueError: not enough values to unpack (expected 2, got 1)`

### ISSUE THREAD

**Issue by abbaahmad** [canonical/jhack#131]
The above command used to work, but I have tried using it since Friday and I keep getting the error. I've also tried 
`jhack utils sync <application-name> -s ./lib -s ./src` and `jhack utils sync <application-name>` and both return `KeyError: 'applications'` error. I'm working with juju 2.9.46-ubuntu-amd64. I'm happy to provide additional information if needed.

**Comment by PietroPasotti** [comment]
Hi @abbaahmad, could you provide the full traceback? It's not obvious to me where the error is originating from.
Please paste the full output after you run `LOGLEVEL=DEBUG jhack utils sync <application-name>`

**Comment by PietroPasotti** [comment]
Never mind! tried it out and you're right. Found a bug I introduced a couple of weeks ago with #128. Working on a fix...
