### ISSUE TITLE
[cosmetic] Examples on help output are all on a single line

### ISSUE THREAD

**Issue by facundofc** [canonical/jhack#141]
```console
$ jhack utils show-relation --help

 Usage: jhack utils show-relation [OPTIONS] [ENDPOINT1] [ENDPOINT2]

 Displays the databags of two applications or units involved in a relation.
 Examples: $ jhack utils show-relation my_app/0:relation_name other_app/2:other_name $ jhack utils show-relation my_app:relation_name other_app/2:other_name $ jhack utils show-relation my_app:relation_name other_app:other_name
```

The examples are all smushed together making them hard to read. This happens both on `latest/stable` (0.3.29) as in `latest/edge` (0.4.0.8).

**Comment by PietroPasotti** [comment]
in the meanwhile I figured out a simple workaround for show-relation. 
It now shows:

![image](https://github.com/canonical/jhack/assets/6230162/2735173a-ed12-4b1c-928c-61ba13677578)

**Comment by PietroPasotti** [comment]
@facundofc should be fixed on edge

**Comment by facundofc** [comment]
It is! Great, thanks!
