### ISSUE TITLE
Add possibility to fire events on `/leader` unit

### ISSUE THREAD

**Issue by taurus-forever** [canonical/jhack#142]
Hi again,

Branched from https://github.com/canonical/jhack/issues/140

Request: can you please add 'jhack fire mycharm/**leader**' feature to fire the event on the leader unit
(as some DB charm evens have to be executed on the leader and we have to search / specify unit manually from juju status).

If it is not possible, please consider to remove/fix `Fired update-status on db2/leader`. At the moment:
```
ubuntu@juju340:~$ jhack fire db2/leader update-status 
ERROR:jhack.simulate_event:cmd juju ssh db2/leader /usr/bin/juju-exec -u db2/leader JUJU_DISPATCH_PATH=hooks/update-status JUJU_MODEL_NAME=az3 JUJU_UNIT_NAME=db2/leader ./dispatch terminated with 1
ERROR:jhack.simulate_event:stdout=b'\x1b[91mERROR\x1b[0m "db2/leader" is not a valid tag\r\n'
ERROR:jhack.simulate_event:stderr=b'ERROR command terminated with exit code 2\n'
Fired update-status on db2/leader.
``` 

Those log line is confusing (as no events have been fired).
Tnx!

**Comment by PietroPasotti** [comment]
in progress

![image](https://github.com/canonical/jhack/assets/6230162/bee1b862-82c2-406f-ba48-ef2be5d810b3)
