### ISSUE TITLE
'jhack tail' is slow to stop after tailing for some time (20 charms, 100+ events, 20 mins)

### ISSUE THREAD

**Issue by taurus-forever** [canonical/jhack#163]
Hi,

After deploying [test bundle](https://pastebin.canonical.com/p/3Z3MhDJKZd/) and `jhack tailing` the process it is slow to abort jhack, the ^C takes time and bring to the another jhack output (all columns shown this time) which you need to abort with another ^C and it takes time, see the recording with speedup:

[Screencast from 2024-06-03 23-39-34.webm](https://github.com/canonical/jhack/assets/1928266/87cb3a0c-fcf0-438c-a5f5-1358d733208f)

**Comment by PietroPasotti** [comment]
I think that's because it's processing so many events.
Is "20 mins" the time it took to close tail (that'd be a lot), or the lifetime of the test model you were deploying?

**Comment by taurus-forever** [comment]
The closing time is 1-2 mins in the worst case... but annoying and visible. It looks like it is doing some internal calculations... as more column shown. Why those calculations necessary?

**Comment by PietroPasotti** [comment]
those calculations are needed to print out the final 'full table', listing all captured events from the start of the session up to when you close it.
If you pass --output ./foo.txt the full table will be printed to file, otherwise it will be printed to console. 
If it's annoying I can disable it (it will still take longer with --output)

**Comment by taurus-forever** [comment]
if no --output passed, can you skip the final calculations and exit? :-)

> If it's annoying I can disable it (it will still take longer with --output)

It is necessary when necessary... otherwise fast.

**Comment by PietroPasotti** [comment]
yeah, thought it'd be nice to see the full summary even without --output, didn't think it'd take annoyingly long on regular runs.

**Comment by PietroPasotti** [comment]
This is probably solved by using the `--printer raw` option implemented in #175
