### ISSUE TITLE
[docs] Add description for difference in color and icons

### ISSUE THREAD

**Issue by taurus-forever** [canonical/jhack#189]
Hi,

For example, `jhack tail` shows me:

![image](https://github.com/user-attachments/assets/f3b13f3c-3588-4ad6-8ba0-30592108b367)

Q: 1) why I have 5 start events on `postgresql/0`?  2) why are they different in color? :-D

I cannot share steps to reproduce, as I am searching it now :-)

It is a ticket to document all the pictograms. Thank you!

**Comment by PietroPasotti** [comment]
Done and [live on main](https://github.com/canonical/jhack?tab=readme-ov-file#event-color-coding)!

**Comment by PietroPasotti** [comment]
I will dig a bit for you on what precisely those operator events mean
